### ISSUE TITLE
Fix: 연동 오류 수정

### ISSUE THREAD

**Issue by zzimnii** [Yorieter/UMC-Yorieter_BE#64]
## ⚙️ 발생 기능
버그가 어떤 기능에서 발견되었는지 작성해주세요.

## ❓ 발생 상황
버그가 어떤 상황에서 발생했는지 작성해주세요.

## 📝 To-do
- [x] 이것저것 수정용

**Comment by SJ-PARKs** [comment]
수고하셨습니당
